- workflow/plots/EEE_plots.ipynb
- workflow/plots/EEE_plots.py
Good day. I have added ghost line for heat demand to better illustrate the retrofitting results.
> Ghost heat demand line

- workflow/configs/original_study/config.flexible.yaml
- workflow/configs/original_study/config.igas_tes.yaml
- workflow/configs/original_study/config.rigid.yaml
Add updates into the configs to keep up-to-date with PyPSA-Eur upstream.
> Update configs upstream

- workflow/plots/EEE_plots.py
Old paths unfortunately did not work on my machine. Does this suggestion work on Windows? @yerbol-akhmetov
> update paths for plots, generalise filenames

- workflow/configs/original_study/config.flexible.yaml
- workflow/configs/original_study/config.igas_tes.yaml
- workflow/configs/original_study/config.rigid.yaml
Good day, here I propose to add `everywhere_powerplants` to all config file becuase of recent update of `config.default.yaml file` and corresponding python scripts. Otherwise it causes error.
> add everywhere_powerplants

- workflow/configs/original_study/config.flexible.yaml
- workflow/configs/original_study/config.igas_tes.yaml
- workflow/configs/original_study/config.rigid.yaml
Here, I propose setting `gas_network` to false.
> no gas_network

- workflow/configs/original_study/config.flexible-industry.yaml
- workflow/configs/original_study/config.flexible.yaml
- workflow/configs/original_study/config.igas_tes-industry.yaml
- workflow/configs/original_study/config.igas_tes.yaml
- workflow/configs/original_study/config.retro_tes-industry.yaml
- workflow/configs/original_study/config.retro_tes.yaml
- workflow/configs/original_study/config.rigid-industry.yaml
- workflow/configs/original_study/config.rigid.yaml
Good day, here I propose changes to configs and addition of config files for industry.
> Add new config for industry

- workflow/configs/EEE_study/config.flexible-industry.yaml
- workflow/configs/EEE_study/config.flexible-moderate.yaml
- workflow/configs/EEE_study/config.igas_tes-industry.yaml
- workflow/configs/EEE_study/config.retro_tes-industry.yaml
- workflow/configs/EEE_study/config.rigid-industry.yaml
Good day. Here I propose an update to scenario configs to change transport share to default number and change cost year to 2040.
> Update configs' cost year and transport share

- Snakefile
- plots/colors.py
- plots/plot_total_costs.py
Good day. Here I have added a fix to plot_costs script that will remove duplicatation of oil. In addition, I have added a plotting script for total system capacity.
> Fix plot bugs

- scripts/set_capacities.py
Good day. Here I propose to add functionality to set `p_nom_min` capacities for future horizons based on `p_nom_opt` from previous horizon for links.
> Set p_nom_min capacities for links

- Snakefile
- plots/plot_electricity_generation.py
Good day, here I propose to simplify text generation of pie chart. Additionally, `plot_all` rule is fixed.
> Simplify generation pies

- .gitignore
- Snakefile
- plots/plot_electricity_generation.py
@yerbol-akhmetov maybe you have a sec to review and add the plots into plot_all rule, or so?
If you know a way to make the location of text automated would be bomb, too! :bomb:
> plot generation charts

- plots/plot_electricity_generation.py
Good day. Here I propose addition of a legend into `plot_electricity_generation` script. In addition, solar utility and solar rooftop were separated.
> Add legend to electricity generation pie charts

- configs/config.plot.yaml
- plots/table_heat_pumps.py
Good day. Here, I propose improvement in calculation of total number of heat pumps based on @martacki and Jozefien Vanbecelaere.
> Fix heat pump calculations

- Snakefile
- plots/plot_total_costs.py
Good day. I propose to add csv file as an output of `plot_total_costs` rule to have tabular data about costs. Additionally, the name of the rigid scenario was fixed to "No Renovation & Green Heating".
> Make csv table for costs and capacities

- Snakefile
- plots/plot_curtailment.py
Good day. Here, I propose addition of script for plotting curtailment and generation of table with curtailment data.
> Plot curtailment

- Snakefile
- plots/plot_electricity_generation.py
- plots/plot_historic_generation.py
Good day. Here, I propose to improve script for plotting electricity mix by grouping gas into fossil fuels. In addition, rule for plotting historic electricity mix was added.
> Improve plot of electricity generation mix

- plots/plot_transmission_congestion.py
Good day. I propose to add legend to transmission congestion plot. The average cost increase for each scenario was added each congestion plot.
> Add legend for congestion plot

- plots/_helpers.py
- plots/plot_co2_level.py
- plots/plot_curtailment.py
- plots/plot_electricity_bills.py
- plots/plot_electricity_for_heat.py
- plots/plot_electricity_generation.py
- plots/plot_heat_tech_ratio.py
- plots/plot_hydrogen_production.py
- plots/plot_total_costs.py
- plots/plot_transmission_congestion.py
- plots/table_heat_pumps.py
- plots/table_infra_savings.py
- scripts/run.py
Good day. Here, I propose to update the naming for the scenarios based on the technical report.
> Fix namings for scenarios

- configs/EEE_study/config.BAU.yaml
- configs/EEE_study/config.flexible-industry_2030.yaml
- configs/EEE_study/config.flexible-industry_2040.yaml
- configs/EEE_study/config.flexible-industry_2050.yaml
- configs/EEE_study/config.flexible-moderate_2030.yaml
- configs/EEE_study/config.flexible-moderate_2040.yaml
- configs/EEE_study/config.flexible-moderate_2050.yaml
- configs/EEE_study/config.retro_tes-industry_2030.yaml
- configs/EEE_study/config.retro_tes-industry_2040.yaml
- configs/EEE_study/config.retro_tes-industry_2050.yaml
- configs/EEE_study/config.rigid-industry_2030.yaml
- configs/EEE_study/config.rigid-industry_2040.yaml
- configs/EEE_study/config.rigid-industry_2050.yaml
- plots/plot_co2_level.py
- plots/plot_total_costs.py
- plots/table_infra_savings.py
Good day, here I propose to update configs to accommodate changes in master of pypsa-eur, where shift was made from OCGT to CCGT. The configs were updated as well as the plots.
> OCGT to CCGT

- plots/plot_co2_level.py
- plots/plot_curtailment.py
- plots/plot_electricity_bills.py
- plots/plot_electricity_for_heat.py
- plots/plot_electricity_generation.py
- plots/plot_heat_tech_ratio.py
- plots/plot_hydrogen_production.py
- plots/plot_total_costs.py
- plots/plot_transmission_congestion.py
- plots/table_heat_pumps.py
- plots/table_infra_savings.py
Good day. Here, I propose to update the scenario names from `green` to `electric` and `optimal heating` to `cost-optimal heating` in plots.
> Update scenario names

- .github/workflows/reuse-compliance.yml
- README.md
- test.py
Good day. I propose to add reuse badge here.
> Reuse badge

- README.md
- scripts/run.py
Good day. Here I propose to fix some minor bugs related to logging and badge.
> fix some bug

- configs/EEE_study/config.BAU.yaml
Good day, I propose to set CO2L0.725 for BAU.
> Fix BAU config

- plots/plot_electricity_generation.py
- plots/plot_historic_generation.py
- plots/plot_total_costs.py
- scripts/run.py
Good day. Here I propose to provide some small improvements such as dpi increase and fixing the size of images. Also one typo in `run.py` is fixed.
> Improve plots

- configs/EEE_study/config.BAU.yaml
- configs/EEE_study/config.flexible-industry_2030.yaml
- configs/EEE_study/config.flexible-industry_2040.yaml
- configs/EEE_study/config.flexible-industry_2050.yaml
- configs/EEE_study/config.flexible-moderate_2030.yaml
- configs/EEE_study/config.flexible-moderate_2040.yaml
- configs/EEE_study/config.flexible-moderate_2050.yaml
- configs/EEE_study/config.retro_tes-industry_2030.yaml
- configs/EEE_study/config.retro_tes-industry_2040.yaml
- configs/EEE_study/config.retro_tes-industry_2050.yaml
- configs/EEE_study/config.rigid-industry_2030.yaml
- configs/EEE_study/config.rigid-industry_2040.yaml
- configs/EEE_study/config.rigid-industry_2050.yaml
Good day. I propose here to update the costs of the decentral heat pumps. The modifications are motivated by `pypsa/pypsa-ariadne`.
> Update decentral heat-pump costs

- README.md
- Snakefile
- configs/config.plot.yaml
- plots/_helpers.py
- plots/plot_capacity_expansion.py
- plots/plot_co2_level.py
- plots/plot_curtailment.py
- plots/plot_electricity_bills.py
- plots/plot_electricity_for_heat.py
- plots/plot_electricity_generation.py
- plots/plot_heat_tech_ratio.py
- plots/plot_hydrogen_production.py
- plots/plot_total_costs.py
- plots/plot_transmission_congestion.py
- plots/table_res_share.py
- scripts/run.py
Good day. Here I propose several changes.
Plots:
Run.py:
Other:
> Minor fixes of plots

- Snakefile
- configs/EEE_study/config.flexible-industry_2040.yaml
- configs/EEE_study/config.flexible-industry_2050.yaml
- configs/EEE_study/config.flexible-moderate_2040.yaml
- configs/EEE_study/config.flexible-moderate_2050.yaml
- configs/EEE_study/config.retro_tes-industry_2040.yaml
- configs/EEE_study/config.retro_tes-industry_2050.yaml
- configs/EEE_study/config.rigid-industry_2040.yaml
- configs/EEE_study/config.rigid-industry_2050.yaml
- plots/plot_co2_level.py
- plots/plot_electricity_for_heat.py
- plots/plot_total_costs.py
- plots/plot_transmission_congestion.py
- scripts/set_capacities.py
Good day. I propose to add a script for calculating CO2 emission savings for each scenario in tCO2_eq and equivalent natural gas volume in m3.
> Add co2 savings
